name: CI

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.3'
          - '8.4'
      fail-fast: false

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
